### ISSUE TITLE
Translation no longer working - Slack UI Change

### ISSUE THREAD

**Issue by tomatnasdaq** [limhenry/slack-translate-extension#1]
Slack updated their UI this week and the "view translation" link is no longer appearing - CSS selector most likely was removed.

**Comment by tomatnasdaq** [comment]
Submitted a PR to fix: https://github.com/limhenry/slack-translate-extension/pull/2

**Comment by serch06** [comment]
Is there a due date for this fix?

**Comment by tomatnasdaq** [comment]
Hey there Sergio, waiting on @limhenry to approve the PR -- i have been using it in developer mode
